### ISSUE TITLE
BUG: Error harvesting users. local variable 'soup' referenced before assignment

### ISSUE THREAD

**Issue by royharoush** [gojhonny/InSpy#1]
Hi,
i get the following on Kali 2. 

root@kaliiso:/tmp/InSpy# python InSpy.py -c cisco

 --------------------------------------------------------------------------
 InSpy v1.0 - LinkedIn Employee Enumerator by Jonathan Broche (@g0jhonny)
 --------------------------------------------------------------------------
 
[*] Searching for employees working at cisco with 'sales' in their title
[!] Timeout enumerating the sales department
[!] Error harvesting users. local variable 'soup' referenced before assignment

**Comment by gojhonny** [comment]
This has been fixed in the latest release.
