### ISSUE TITLE
How to run bot

### ISSUE THREAD

**Issue by jayhill365** [gojhonny/InSpy#2]
I've git cloned and then ran the pip install -r requirments in the right directory however when I run the code python Inspy.py all I get is the readme document. What am I missing here ?

**Comment by gojhonny** [comment]
Can you show me an example of the command you're using? InSpy has two functionalities: techspy and empspy. Make sure you're supplying it with one of those arguments and a company name.

**Comment by jayhill365** [comment]
That's probably the problem I didn't know how to specify the command within the Inspy.py document Ill share the pics I took of my terminal and the Inspy.py doc I've edited

**Comment by jayhill365** [comment]
<img width="1114" alt="screen shot 2017-01-18 at 2 16 35 pm" src="https://cloud.githubusercontent.com/assets/19259608/22085500/3346d03e-dd89-11e6-9b56-90e298d83dc2.png">
<img width="1125" alt="screen shot 2017-01-18 at 2 16 50 pm" src="https://cloud.githubusercontent.com/assets/19259608/22085499/33436926-dd89-11e6-96a8-e3d669cbda78.png">
<img width="1131" alt="screen shot 2017-01-18 at 2 16 58 pm" src="https://cloud.githubusercontent.com/assets/19259608/22085498/33412f3a-dd89-11e6-9ca1-8bc6f55127ab.png">
<img width="599" alt="screen shot 2017-01-18 at 2 17 13 pm" src="https://cloud.githubusercontent.com/assets/19259608/22085526/3f74cfc8-dd89-11e6-9dbe-ff41528528ab.png">

**Comment by gojhonny** [comment]
No need to modify source code. Try running `python Inspy.py Microsoft --empspy`

**Comment by jayhill365** [comment]
OK I ran python InSpy.py Microsoft --empspy and this is what I got. Is there a way to specify location
<img width="764" alt="screen shot 2017-01-18 at 2 54 05 pm" src="https://cloud.githubusercontent.com/assets/19259608/22086605/61912b2e-dd8e-11e6-9d94-6b5456b174fa.png">
<img width="731" alt="screen shot 2017-01-18 at 2 54 14 pm" src="https://cloud.githubusercontent.com/assets/19259608/22086610/69fadec2-dd8e-11e6-9819-582713aa5422.png">

**Comment by gojhonny** [comment]
Great, seemed like it worked. Feel free to ping me with any additional questions. I'm going to go ahead and close this issue out.

**Comment by jayhill365** [comment]
OK thanks

**Comment by jayhill365** [comment]
Thanks so much.. Can you briefly explain how to run the --emailformat command?

**Comment by gojhonny** [comment]
Sure thing, just provide --emailformat with one of the allowed formats (they can be found with the help command). For example: `python InSpy.py Acme --empspy --emailformat flast@acme.org`

**Comment by jayhill365** [comment]
Sure thing thanks again it's working!

**Comment by jayhill365** [comment]
Thought I had it all figured out but still can't seem to figure out the email command. I'm just getting a log of employees and their job titular when running "python Inspy.py Microsoft --empspy --emailformat john@microsoft.com

**Comment by jayhill365** [comment]
<img width="595" alt="screen shot 2017-01-19 at 8 46 40 am" src="https://cloud.githubusercontent.com/assets/19259608/22116026/06266830-de24-11e6-8aa9-b1cd4fa556ad.png">
<img width="1031" alt="screen shot 2017-01-19 at 8 47 22 am" src="https://cloud.githubusercontent.com/assets/19259608/22116027/0640040c-de24-11e6-866b-0af7536e4563.png">
