### ISSUE TITLE
Update for a more recent Python requests module

### ISSUE THREAD

**Issue by sbrun** [gojhonny/InSpy#4]
Hi,
I started to package this tool for Kali Linux. For the dependencies we use the packaged modules in the distro and we have requests version 2.18.1.
It fails with the message "Error: Invalid return character or leading space in header: User-Agent"
It would be nice if you can fix this.
For Kali I add this patch:
```
-headers={'Host':'www.linkedin.com', 'User-Agent': '    Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
+headers={'Host':'www.linkedin.com', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'}
```

**Comment by gojhonny** [comment]
Hello, I have removed the white space from the headers under crawler.py. Let me know if there's anything else you need.

**Comment by sbrun** [comment]
thanks for the changes. I think you can close this issue.
inspy is in kali-rolling now but it hasn't been tested yet (I'm just the "packager")
